[package]
name = "receipt_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
pdfium-render = "0.8"
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tesseract = "0.15.1"
tokio = { version = "1", features = ["full"] }
plotters = "0.3.0"
chrono = "0.4.40"
