services:
  # Development environment with code mounted from host
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app                        # Mount your code
      - cargo-cache:/usr/local/cargo   # Cache dependencies
      - target-cache:/app/target       # Cache build artifacts
      - ./receipts:/app/receipts       # Mount your receipts directory to process
      - ./results:/app/results         # Mount a directory for output files
    environment:
      - CARGO_TARGET_DIR=/app/target
      - OUTPUT_PATH=/app/results
    ports:
      - "8000:8000"  # Adjust if your app exposes a port
    
  # Production build (only used when needed)
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./receipts:/app/receipts       # Mount your receipts directory
      - ./results:/app/results         # Mount same output directory
    environment:
      - OUTPUT_PATH=/app/results
    ports:
      - "8001:8000"  # Adjust based on your app

volumes:
  cargo-cache:
  target-cache: